[package]
name = "stwo-web-stark"
version = "0.1.0"
authors = ["Bartosz Nowak <bartekn337@gmail.com>"]
edition = "2018"

[patch.crates-io]
sonic-rs = { git = "https://github.com/clealabs/sonic-rs", branch = "fix-wasm" }
# schemars = { git = "https://github.com/GREsau/schemars", rev = "92cfcf6" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
getrandom = { version = "0.3" }
#bytemuck = { version = "1.20.0", features = ["derive"] }
#hashbrown = "0.15.5"
serde = "1.0.134"
serde_json = "1.0.134"
thiserror-no-std = "2.0.2"
cairo-air = { git = "https://github.com/clealabs/stwo-cairo", branch = "62c3c4a-fix-wasm" }
cairo-lang-runner = { git = "https://github.com/clealabs/cairo.git", branch = "fix-wasm64" }
stwo-cairo-adapter = { git = "https://github.com/clealabs/stwo-cairo", branch = "62c3c4a-fix-wasm", default-features = false}
stwo_cairo_prover = { git = "https://github.com/clealabs/stwo-cairo", branch = "62c3c4a-fix-wasm" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", rev = "b1a91f929b5fa29a1a2e9e6990a68a1220c0c673", features = ["mod_builtin"], default-features = false}
cairo-prove = { git = "https://github.com/clealabs/stwo-cairo", branch = "fix-wasm64-standalone"}

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3

[profile.dev]
opt-level = 1
incremental = true

[package.metadata.wasm-pack.profile.release]
#wasm-opt = ['-O0']